---
- name: "SECTION4 | 4.1.3 | Ensure ufw service is enabled | enable service"
  ansible.builtin.systemd_service:
    name: ufw.service
    daemon_reload: true
    enabled: false
    masked: no
    state: stopped
- name: "SECTION4 | 4.1.3 | Ensure ufw service is enabled | enable ufw"
  community.general.ufw:
    state: disabled