---
- hosts: all
  gather_facts: no

  tasks:
  -  name: Root FS usage
     shell: df -h / |awk ' { print $5 } ' |grep -v Use
     register: dfroot

  -  debug:
       msg: "System {{ inventory_hostname }}'s root FS utiliation is {{ dfroot.stdout }}"
