---
- name: Power on a virtual machine
  vmware_guest:
    hostname: 192.168.0.201
    username: awxuser@vsphere.local
    password: Fenerbahce1907
    validate_certs: false
    name: "{{ vm_name }}"
    state: poweredon
  delegate_to: localhost
  register: deploy