---
- name: Wait for the virtual machine to shutdown
  community.vmware.vmware_guest_powerstate:
    hostname: 192.168.0.201
    username: awxuser@vsphere.local
    password: Fenerbahce1907
    validate_certs: false
    name: "{{ vm_name }}"
    state: shutdown-guest
    state_change_timeout: 200
  delegate_to: localhost
  register: deploy