---
- name: Wait for the virtual machine to shutdown
  vmware_guest:
    hostname: 192.168.0.201
    username: awxuser@vsphere.local
    password: Fenerbahce1907
    validate_certs: false
    name: "{{ vm_name }}"
    state: shutdownguest
    state_change_timeout: 200
  delegate_to: localhost
  register: deploy
