---
- name: check zabbix agent file
  stat:
    path: /etc/zabbix/zabbix_agentd.conf
  register: zabbix

- name: backup zabbix conf
  command: cp /etc/zabbix/zabbix_agentd.conf /etc/zabbix/zabbix_agentd.conf.backup
  when: zabbix.stat.exists == True 

- name: Debug message
  debug:
    msg: "{{ inventory_hostname }}: no zabbix agent"
  when: zabbix.stat.exists == False

- name: Remove the wrong ostname at zabbix agend conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    state: absent
    line: 'Hostname=centos7_template_for_clone.host.gittigidiyor.net'
  when: zabbix.stat.exists == True 

- name: Set the hostname at zabbix agend conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    line: 'Hostname={{ inventory_hostname }}.host.gittigidiyor.net'
  when: zabbix.stat.exists == True 
  notify: restart zabbix
