---
- name: check zabbix agent file
  stat:
    path: /etc/zabbix/zabbix_agentd.conf
  register: zabbix

- name: Remove the wrong ServerActive at zabbix agend conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    state: absent
    line: 'ServerActive=bslsysmon03.host.gittigidiyor.net'
  when: zabbix.stat.exists == True 

- name: Set the ServerActive at zabbix agend conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    line: 'ServerActive=bslsyspmon03.host.gittigidiyor.net'
  when: zabbix.stat.exists == True 

- name: Remove the Server at zabbix agend conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    state: absent
    line: 'Server=bslsysmon03.host.gittigidiyor.net'
  when: zabbix.stat.exists == True 

- name: Set the Server at zabbix agend conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    line: 'Server=bslsyspmon03.host.gittigidiyor.net'
  when: zabbix.stat.exists == True 
  notify: restart zabbix
